[package]
name = "gandiva"
version = "0.14.0-SNAPSHOT"
license = "Apache-2.0"
description = "A tool set for compiling and evaluating expression against arrow data"
homepage = "https://github.com/apache/arrow"
repository = "https://github.com/apache/arrow"
authors = ["Apache Arrow <dev@arrow.apache.org>"]
keywords = [ "arrow", "parquet", "hadoop" ]

[dependencies]
libc = "0.2"
arrow = { path = "../arrow" }
